#!/bin/sh

# Main script for running simulations
# example of call: ./Allrun 3
# First argument: number of processors to be used for calculation (Integer value)

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

ERROR_CODE=$?
if [ $ERROR_CODE -ne 0 ]; then
    echo -e "\nError:"
    echo -e "OpenFOAM run functions not found\n" >&2
    exit $ERROR_CODE
fi

application=$(getApplication)

if [ ! -d "constant/polyMesh" ]; then
    ./preRun
fi

ERROR_CODE=$?
if [ $ERROR_CODE -ne 0 ]; then
    exit $ERROR_CODE
fi

if [ $1 -eq 1 ]; then
    echo "Running $application on $PWD"
    ./runApp $1 > log_cfd.txt
    cp system/updatingFiles/controlDict.1 system/controlDict
    cp system/updatingFiles/fvSolution.1 system/fvSolution
    cp system/updatingFiles/fvSchemes.0 system/fvSchemes
    cp 0.bkp/p_env* 0.001/
    ./runApp $1 > log_mixing.txt
else
    m4 -D NUM=$1 < system/decomposeParDict.m4 > system/decomposeParDict

    ./decompose

    ERROR_CODE=$?
    if [ $ERROR_CODE -ne 0 ]; then
        exit $ERROR_CODE
    fi

    echo "Running $application in parallel on $PWD using $1 processes"
    mpirun -np $1 --output-filename log_cfd ./runApp $1 > /dev/null 2>&1
    cp system/updatingFiles/controlDict.1 system/controlDict
    cp system/updatingFiles/fvSolution.1 system/fvSolution
    cp system/updatingFiles/fvSchemes.0 system/fvSchemes

    if [ $? -eq 0 ]; then
        ./reconstruct

        if [ $? -eq 0 ]; then
            rm -rf processor*
        fi
    fi

    cp 0.bkp/p_env* 0.001/
    ./decompose

    ERROR_CODE=$?
    if [ $ERROR_CODE -ne 0 ]; then
        exit $ERROR_CODE
    fi

    echo "Running $application in parallel on $PWD using $1 processes"
    mpirun -np $1 --output-filename log_mixing ./runApp $1 > /dev/null 2>&1

    if [ $? -eq 0 ]; then
        ./reconstruct

        if [ $? -eq 0 ]; then
            rm -rf processor*
        fi
    fi

fi

postProcess -func writeCellVolumes -latestTime

cp ../p_env1 10.001/
cp ../p_env3 10.001/
cp ../k 10.001/
cp ../epsilon 10.001/
cp ../phi 10.001/
