#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

unzip polyMesh.zip -d ./constant/polyMesh
ERROR_CODE=$?
if [ $ERROR_CODE -ne 0 ]; then
    echo -e "\nError:"
    echo -e "Mesh extraction failed!\n" >&2
    exit $ERROR_CODE
fi
