#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# set -x

if [ ! -d "0.bkp" ]; then
    cp -r 0 0.bkp
elif [ -d "0" ]; then
    rm -rf 0
    cp -r 0.bkp 0
fi

# { set +x; } 2>/dev/null

# runApplication -overwrite topoSet
# runApplication -overwrite setFields
