#!/bin/bash

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication -overwrite reconstructPar -newTimes
ERROR_CODE=$?
if [ $ERROR_CODE -ne 0 ]; then
    echo -e "\nError:"
    echo -e "Domain decomposition failed! Check the corresponding log file.\n" >&2
    exit $ERROR_CODE
fi
