#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf constant/polyMesh/boundary > /dev/null 2>&1
cleanCase

if [ -d "0.bkp" ]; then
    rm -rf 0
    mv 0.bkp 0
fi
